apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: dev
spec:
  replicas: 1   # Dev usually runs single replica to save cost
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: 454331167189.dkr.ecr.us-east-1.amazonaws.com/eks-iac-ci-cd-project:latest
          ports:
            - containerPort: 81
          env:
            - name: ENV
              value: "dev"
