apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-iac-ci-cd-project
  namespace: qa
spec:
  replicas: 2   # QA runs with more replicas for testing stability
  selector:
    matchLabels:
      app: eks-iac-ci-cd-project
  template:
    metadata:
      labels:
        app: eks-iac-ci-cd-project
    spec:
      containers:
        - name: eks-iac-ci-cd-project-container
          image: 454331167189.dkr.ecr.us-east-1.amazonaws.com/eks-iac-ci-cd-project:latest
          ports:
            - containerPort: 81
          env:
            - name: ENV
              value: "qa"
